INVENTORY_TABLE = {
    0: 'Medicinal herb',
    1: 'Strong medicine',
    2: 'Special medicine',
    3: 'Multi medicine',
    4: 'Yggdrasil dew',
    5: 'Magic elixir',
    6: 'Sage\'s elixir',
    7: 'Elfin elixir',
    8: 'Yggdrasil leaf',
    9: 'Antidotal herb',
    10: 'Moonwort bulb',
    11: 'Panacea',
    12: 'Antimagic powder',
    13: 'Oomph powder',
    14: 'Wizard\'s penny',
    15: 'Wizard\'s shilling',
    16: 'Insulade',
    17: 'Jumbo Insulade',
    18: 'Seed of skill',
    19: 'Seed of life',
    20: 'Seed of magic',
    21: 'Seed of strength',
    22: 'Seed of defence',
    23: 'Seed of agility',
    24: 'Seed of wisdom',
    25: 'Monster manure',
    27: 'Loyalty card',
    28: 'Gold nugget',
    29: '\'Positive Puller\'',
    30: '\'Think Negative\'',
    31: '\'Neutral Ground\'',
    32: 'Amor seco essence',
    41: 'Metal ticket',
    44: 'Beastie bites',
    45: 'Smelling salts',
    47: 'Book of Wulfspade',
    48: 'Book of Hawkhart',
    49: 'Book of Diamagon',
    50: 'Book of Cluboon',
    51: 'Warrior\'s scroll',
    52: 'Mage\'s scroll',
    53: 'Priest\'s scroll',
    54: 'Martial artist\'s scroll',
    55: 'Sage\'s scroll',
    56: 'Thief\'s scroll',
    57: 'Pinball',
    58: 'Rockbomb shard',
    60: 'Mistake medicine',
    65: 'Timbrel of tension',
    66: 'Sag powder',
    67: 'Sapperine',
    68: 'Deceleratonic',
    69: 'Dimium',
    70: 'Bufferine',
    71: 'Acceleratonic',
    72: 'Pingium',
    73: '\'The Healing Touch\'',
    74: '\'Secret Sorcery\'',
    75: '\'Brawn Over Brains\'',
    76: '\'Duck and Cover\'',
    77: '\'Life in the Fast Lane\'',
    78: '\'Knowledge is Power\'',
    79: 'Mysterious medal',
    80: 'Bemusoleum key',
    81: 'Scout ring',
    82: 'Soggy letter',
    83: '\'Head Over Heals\'',
    92: 'Pretty pebble',
    93: 'Bronze bit',
    94: 'Silver sliver',
    106: 'Machine parts',
    108: 'Medal of Merit',
    110: 'Heart of mud',
    111: 'Copper Sword', #begin weapons
    112: 'Divine dagger',
    113: 'Rapier',
    114: 'Steel broadsword',
    115: 'Zombiesbane',
    116: 'Dragonsbane',
    117: 'Obsidian sword',
    118: 'Silver broadsword',
    119: 'Zombiesblight',
    120: 'Dragonsblight',
    121: 'Giant\'s sword',
    122: 'Zombie slayer',
    123: 'Dragon slayer',
    124: 'Lost katana',
    125: 'Metal king sword',
    126: 'Iron lance',
    127: 'Pitchfork',
    128: 'Sacred spear',
    129: 'Partisan',
    130: 'Holy lance',
    131: 'Hunting spear',
    132: 'Dragon lance',
    133: 'Halbert',
    134: 'Hero spear',
    135: 'Gáe Bolg',
    136: 'Stone axe',
    137: 'Woodcutter\'s axe',
    138: 'Iron ace',
    139: 'Woordman\'s axe',
    140: 'Headsman\'s axe',
    141: 'Battleaxe',
    142: 'Forester\'s axe',
    143: 'King axe',
    144: 'Ranger\'s axe',
    145: 'Executioner\'s axe',
    146: 'Oaken club',
    147: 'Sludgehammer',
    148: 'Iron hammer',
    149: 'War hammer',
    150: 'Miracle mallet',
    151: 'Giant\'s wrench',
    152: 'Sledgehammer',
    153: 'Marauder\'s maul',
    154: 'Warlord\'s hammer',
    155: 'Miracle mace',
    156: 'Leather whip',
    157: 'Battle whip',
    158: 'Thorn whip',
    159: 'Sidewinder',
    160: 'Snakeskin whip',
    161: 'Chain whip',
    162: 'Dragontail whip',
    163: 'Spiked steel whip',
    164: 'Scourge whip',
    165: 'Gringham whip',
    166: 'Stone claws',
    167: 'Metal claws',
    168: 'Iron claws',
    169: 'Sacred claws',
    170: 'Razor claws',
    171: 'Steel claws',
    172: 'Metal talons',
    173: 'Gryphon talons',
    174: 'Sacred talons',
    175: 'Orichalcum claws',
    176: 'Cypress staff',
    177: 'Rune staff',
    178: 'Phoenix sceptre',
    180: 'Plus sceptre',
    181: 'Minus sceptre',
    182: 'Crystal staff',
    183: 'Staff of darkness',
    184: 'Sage\'s staff',
    185: 'Royal rod',
    186: 'Leonine greatsword',
    187: 'Schleiman shooter',
    188: 'Malevomace',
    189: 'Ebony talons', 
    190: 'Diablo spear', 
    193: 'Paws',
    194: 'Pile-on',
    195: 'Miracle sword',
    196: 'Falcon claws',
    197: 'Staff of Ghent',
    198: 'Dragon claws',
    199: 'Graco\'s trident'
 }

class Weapon:
    def __init__(self, buffer, idx):
        pass

class Item:
    def __init__(self, buffer, idx):
        pass